### ISSUE TITLE
Added and error-screen that is presented to the user in case code in Pyodide results in a crash

### ISSUE THREAD

**Issue by trbKnl** [eyra/port#36]
# Problem

If code in `script.py` results in a crash, the participant is not notified and waits indefinitely watching a spinner animation

# Change

in `py_worker.js` a try catch block has been added that catches errors resulting from pyodide crashes. The error is stringyfied and presented on a page.

**Comment by trbKnl** [comment]
commit 32879b1

**Comment by emielvdveen** [comment]
That's what we needed
