### ISSUE TITLE
Pre-review comment on JOSS submission

### ISSUE THREAD

**Issue by osorensen** [eyra/port#37]
Here are a few suggested changes after my first reading of your [JOSS submission](https://github.com/openjournals/joss-reviews/issues/5558). Please update the paper before we start the review.

- On line 43, there seems to be a redundant right parenthesis:
<img width="825" alt="image" src="https://github.com/eyra/port/assets/21175639/da590c45-0c17-481d-b642-9613387390a3">

- On line 73, abbreviation OSD2F should be introduced:
<img width="735" alt="image" src="https://github.com/eyra/port/assets/21175639/bb160c91-73d3-4309-aa13-2197d7ad542c">

- On lines 80-81, there should either be a comma after "controller" or you should change "i.e," to "That is,":
<img width="738" alt="image" src="https://github.com/eyra/port/assets/21175639/64db1bda-8cf0-4ac8-ba8e-3c285224a44c">

- Line 132, change from "scriptextracts" to "script extracts": 
<img width="741" alt="image" src="https://github.com/eyra/port/assets/21175639/9884cd2e-6d94-403e-a453-027e7262fd4f">

**Comment by trbKnl** [comment]
See #40

**Comment by lauraboeschoten** [comment]
Thanks @osorensen for the suggested changes. We just updated the manuscript accordingly.
