### ISSUE TITLE
Include example usage

### ISSUE THREAD

**Issue by lauraboeschoten** [eyra/port#44]
**Comments by reviewers:**

- Example Usage: Though there are instructions on how to host it online, there isn't any example/demo website that I can try. It would be great if the authors could add a video of implementing Port on a live website or something similar.
- Example usage: There could be at least one example of use available.

**I suggest to include in the main text:**

under the tab “Port + Next on the Azure Cloud (Recommended)”: Terraform configuration files to host Port on Azure can be found in the following repository: https://github.com/d3i-infra/infrastructure-d3i-pilot

under the tab “Port API examples” include an additional header with: Example applications of Port: 
o	https://github.com/d3i-infra/port-d3i-pilot
o	https://github.com/d3i-infra/port-vu-pilot
o	https://github.com/d3i-infra/port-news-dynamics
o	https://github.com/d3i-infra/port-pilot-netflix

**Comment by trbKnl** [comment]
The [wiki](https://github.com/eyra/port/wiki) contains a list of previous studies.

I will add a header below "Port API examples" called "Port previous studies". With a reference to the port wiki.

**Comment by trbKnl** [comment]
Close #97f6bca

**Comment by trbKnl** [comment]
see: Commit 97f6bca on master
